### ISSUE TITLE
Consider new command syntax

### ISSUE THREAD

**Issue by mackelito** [AlisonVilela/ngx-zendesk-webwidget#17]
Zendesk api has an updated command syntax as replacement for the old legacy zE methods.
Is there a plan to support the new format? :) 

https://developer.zendesk.com/embeddables/docs/widget/introduction

**Comment by kurtj** [comment]
I think that I was actually able to use the new syntax and better yet, was able to load the module, then populate these contact form fields AFTER my user had logged into app so that only authenticated users can contact us this way and we populate the contact form with their username.

Code snippet example below:  If this works for others - maybe add as example in readme?  Took some tinkering to figure out, for some reason I ended up having to use both new (for custom fields) and old syntax (for Name/email).

      this._ngxZendeskWebwidgetService.setSettings({
        webWidget: {
          contactForm: {
            fields: [
              { id: '1234', prefill: { '*': LoginInfoObj.UserName } }
            ]
          }
        }
      });
      this._ngxZendeskWebwidgetService.identify({
        name: 'My prepopulated name field for contact form',
        email: 'My prepopulated email field for contact form'
      });
