### ISSUE TITLE
"this._NgxZendeskWebWidgetService.zE is not a function"

### ISSUE THREAD

**Issue by diomededavid** [AlisonVilela/ngx-zendesk-webwidget#40]
When I add configuration options to the webwidget service I get an error returned 

"this._NgxZendeskWebWidgetService.zE is not a function"

**Comment by roymckrank** [comment]
Same for me, did you find any workaround?

**Comment by diomededavid** [comment]
Sorry, I did not. I also have tried, which is easier to deal with.

https://www.bennadel.com/blog/3248-the-zendesk-web-widget-appears-to-have-a-small-hide-show-race-condition.htm

https://www.bennadel.com/blog/3249-wrapping-the-zendesk-web-widget-in-a-promise-based-zendesk-service-in-angular-2-4-9.htm

**Comment by millerhorvath** [comment]
I also had this problem. The issue a had is that I was trying to call `zE` before the `initZendesk` method finished to run. The `initZendesk` is called by the `NgxZendeskWebwidgetService` class constructor (if the `lazyLoad` parameter is set as `false`) and is the functions that sets the `zE` parameter as a function.

The workaround I found is using the lazyLoad and calling the `initZendesk` in `onInit` method instead of in the component constructor using `await`, to make sure the `initZendesk` finish before I call `zE`.

#### Component code:

```import { Component, OnInit } from '@angular/core';
import { NgxZendeskWebwidgetService } from 'ngx-zendesk-webwidget';
import { ZendeskConfig } from '../models/zendeskConfig';

@Component({
  selector: 'app-zendesk-example',
  templateUrl: './zendesk-example.component.html',
  styles: []
})
export class ZendeskExampleComponent implements OnInit {

  constructor(private zendeskService: NgxZendeskWebwidgetService) {
    console.log(this.zendeskService.isInitialized());
    console.log(this.zendeskService.zE);
  }

  async ngOnInit() {
    await this.zendeskService.initZendesk(new ZendeskConfig());
    this.zendeskService.zE('webWidget', 'show');
    console.log(this.zendeskService.isInitialized());
    console.log(this.zendeskService.zE);
  }
}
```

#### Console outputs:

![image](https://user-images.githubusercontent.com/15879648/80546654-a1ba7680-898c-11ea-970a-69dfb701655c.png)

Look that the outputs from the component constructor shows that the `NgxZendeskWebwidgetService` had not loaded yet (This also happens if you do not set `lazyLoad`).

I hope that helps!
